#!/usr/bin/env bash

set -eu

# -- Source APT commands as functions.
# shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


# -- Install Nitrux base.

NITRUX_BASE_PKGS='
	base-files
	nitrux-minimal-legacy
	nitrux-standard-legacy
'

NITRUX_HW_PKGS='
	nitrux-hardware-drivers-legacy
'

install $NITRUX_BASE_PKGS $NITRUX_HW_PKGS
