#!/usr/bin/env bash

set -eu

# -- Source APT commands as functions.
# shellcheck source=/dev/null

source /configs/scripts/others/apt-funcs


# -- Add Waydrdoid repository.

add_repo_keys \
	90E51522 \
	1DCEE19C > /dev/null

cp /configs/files/sources/sources.list.waydroid /etc/apt/sources.list.d/waydroid-repo.list

update


# -- Install these packages first because libappimageupdate and zsync2 provide files found in other packages.

ZSYNC_LIBAIU_PKGS='
	libappimage1.0
	libappimageupdate
	zlib1g-dev
	zsync2
'

install_force_overwrite $ZSYNC_LIBAIU_PKGS

NX_DESKTOP_PKG='
	nx-desktop-legacy
	nx-desktop-wayland-legacy
	nx-desktop-appimages-vfio
	nx-desktop-apps-vfio
'

FH_SIGH_PKGS='
	polkit-kde-agent-1=4:5.27.11-1
	network-manager-openconnect
	plasma-desktop
	plasma-gamemode
	plasma-widgets-addons
	nx-desktop-apps-legacy
	aide
	aide-common
	btrfs-progs
	firejail
	firejail-profiles
	kexec-tools
	plasma-workspace-wayland

'

install $NX_DESKTOP_PKG $FH_SIGH_PKGS

rm /etc/apt/sources.list.d/waydroid-repo.list

remove_repo_keys \
	90E51522 \
	1DCEE19C > /dev/null

update
