#!/usr/bin/env bash

set -eu

# -- Source APT commands as functions.
# shellcheck source=/dev/null

source "$PWD"/configs/scripts/others/apt-funcs


# -- Remov ebuild sources. 
rm \
	/etc/apt/preferences.d/* \
	/etc/apt/sources.list \
	/etc/apt/sources.list.d/* \
	/usr/share/keyrings/* || true

update


#	Unhold initramfs and casper packages.

INITRAMFS_CASPER_PKGS='
	casper
	initramfs-tools
	initramfs-tools-core
	initramfs-tools-bin
'

unhold $INITRAMFS_CASPER_PKGS
